/**
 * OM-A880 Hardware POS Abstraction Layer (ECR Integration)
 * 
 * The KIOSK app acts as an ECR controller that sends transaction commands to the POS
 * and listens asynchronously for status updates and final transaction results.
 * 
 * All card reading, NFC, PIN entry, EMV processing, encryption, and bank communication
 * are handled entirely by the OM-A880 POS.
 * 
 * The KIOSK app must NOT process, store, or interpret card data.
 * 
 * Supported connection modes:
 * - USB (Auto-detect): Uses Android USB Host / Serial APIs
 * - Ethernet (TCP/IP): Uses TCP socket with timeout and retry
 * 
 * Compatible devices:
 * - Samsung Galaxy A13/A33 (trial phase)
 * - Sunmi Flex 3 (production)
 */

import {
  initializeUSBHost,
  isUSBHostAvailable,
  scanForDevices,
  connectToDevice,
  sendData as sendUSBData,
  disconnect as disconnectUSB,
  getConnectionState as getUSBConnectionState,
  getConnectedDevice,
  onConnectionStateChange as onUSBStateChange,
  onDataReceived as onUSBDataReceived,
  setKeepScreenAwake,
  USBDeviceInfo,
  DEFAULT_POS_IDENTIFIERS,
} from './usbHostService';

import {
  ECR_COMMANDS,
  INTERMEDIATE_MESSAGES,
  ERROR_CODES as ECR_ERROR_CODES,
  parseXMLResponse as parseECRXMLResponse,
  getErrorInfo,
  getIntermediateMessageInfo,
  isSuccessResponse,
  formatAmountForECR,
  ECRResponse,
} from './ecrProtocol';

// Connection types
export type ConnectionType = 'usb' | 'ethernet';

// POS Connection Status
export type ConnectionStatus = 'disconnected' | 'connecting' | 'connected' | 'ready' | 'error';

// Transaction Status (final states)
export type TransactionStatus = 'idle' | 'pending' | 'processing' | 'approved' | 'declined' | 'cancelled' | 'timeout' | 'error' | 'reversal_required';

// Intermediate POS Status Messages
export type POSIntermediateStatus = 
  | 'INITIALIZING'
  | 'INSERT_CARD'
  | 'TAP_CARD'
  | 'SWIPE_CARD'
  | 'ENTER_PIN'
  | 'PIN_ENTERED'
  | 'PROCESSING'
  | 'COMMUNICATING_WITH_BANK'
  | 'RESPONSE_RECEIVED'
  | 'REMOVE_CARD'
  | 'CARD_REMOVED'
  | 'PRINTING_RECEIPT'
  | 'TRANSACTION_COMPLETE'
  | 'TRANSACTION_FAILED'
  | 'REVERSAL_IN_PROGRESS'
  | 'FALLBACK';

// POS Configuration
export interface POSConfig {
  connectionType: ConnectionType;
  ipAddress?: string;
  port?: string;
  timeout?: number; // milliseconds
  retryAttempts?: number;
  // USB specific configuration
  vendorId?: number;
  productId?: number;
  autoDetect?: boolean;
}

// Transaction Request
export interface TransactionRequest {
  transactionId: string;
  amount: number; // in baisas - will be formatted as integer without decimals
  merchantReference?: string; // optional donation ID (max 22 chars)
  currency?: string;
}

// POS XML Response (from OM-A880)
export interface POSXMLResponse {
  success: boolean;
  responseCode: string;
  responseMessage: string;
  transactionAmount: string;
  rrn: string; // Bank Transaction Reference (RRN)
  authCode: string; // Authorization Code
  tid: string; // Terminal ID
  mid: string; // Merchant ID
  cardLastFour?: string;
  cardType?: string;
  receiptData?: string; // Raw receipt data for printing
  rawXML?: string; // Original XML for debugging
  batchNo?: string;
  invoiceNo?: string;
  sequenceNo?: string;
  entryMode?: string;
  txnStatus?: string;
}

// Transaction Response (unified format for app)
export interface TransactionResponse {
  success: boolean;
  transactionId: string;
  // System reference (generated by app - remains unchanged)
  systemReference?: string;
  // POS/Bank references
  posRRN?: string; // Bank Transaction Reference
  posAuthCode?: string; // Authorization Code
  posTID?: string; // Terminal ID
  posMID?: string; // Merchant ID
  posResponseCode?: string;
  // Card info (for display only - no storing sensitive data)
  cardLastFour?: string;
  cardType?: string;
  // Receipt
  receiptData?: string;
  // Error handling
  errorCode?: string;
  errorMessage?: string;
  rawResponse?: POSXMLResponse;
}

// ECR Command Types
export type ECRCommand = 
  | 'PURCHASE'
  | 'REFUND'
  | 'VOID'
  | 'CANCEL'
  | 'GET_STATUS'
  | 'RECONCILIATION'
  | 'GET_TOTALS'
  | 'GET_TERMINAL_INFO'
  | 'LAST_TRANSACTION_STATUS'
  | 'DELETE_BATCH'
  | 'DELETE_REVERSAL';

// POS Message Protocol
export interface POSMessage {
  command: ECRCommand;
  payload?: {
    amount?: string; // Integer string without decimals: 2.000 OMR → "2000"
    transactionId?: string;
    merchantReference?: string;
    invoiceNumber?: string;
  };
}

// POS Status Response
export interface POSStatusResponse {
  ready: boolean;
  printerStatus: 'ok' | 'paper_out' | 'error';
  readerStatus: 'ok' | 'card_present' | 'error';
  connectivity: 'online' | 'offline';
  terminalId?: string;
  merchantId?: string;
  appVersion?: string;
  serialNo?: string;
  batchNo?: string;
}

// Reconciliation Response
export interface ReconciliationResponse {
  success: boolean;
  totalTransactions: number;
  totalAmount: number;
  batchNumber: string;
  timestamp: string;
  result: 'failed' | 'rejected' | 'accepted' | 'accepted_with_upload';
}

// Event callbacks
type StatusCallback = (status: ConnectionStatus) => void;
type TransactionCallback = (response: TransactionResponse) => void;
type IntermediateStatusCallback = (status: POSIntermediateStatus, message: string) => void;

// Internal state
let currentConfig: POSConfig | null = null;
let connectionStatus: ConnectionStatus = 'disconnected';
let transactionStatus: TransactionStatus = 'idle';
let currentIntermediateStatus: POSIntermediateStatus | null = null;
let statusListeners: StatusCallback[] = [];
let transactionListeners: TransactionCallback[] = [];
let intermediateStatusListeners: IntermediateStatusCallback[] = [];
let connectionCheckInterval: ReturnType<typeof setInterval> | null = null;
let lastHandshakeTime: number | null = null;
let lastErrorMessage: string | null = null;

// Default configuration
const DEFAULT_CONFIG: Partial<POSConfig> = {
  timeout: 120000, // 2 minutes for POS transactions
  retryAttempts: 3,
  autoDetect: true,
};

// Intermediate status messages (Arabic) - mapped from ECR protocol codes
const INTERMEDIATE_STATUS_MESSAGES: Record<POSIntermediateStatus, string> = {
  'INITIALIZING': 'جاري التهيئة...',
  'INSERT_CARD': 'الرجاء إدخال البطاقة',
  'TAP_CARD': 'الرجاء تقريب البطاقة',
  'SWIPE_CARD': 'الرجاء تمرير البطاقة',
  'ENTER_PIN': 'الرجاء إدخال الرقم السري',
  'PIN_ENTERED': 'تم إدخال الرقم السري',
  'PROCESSING': 'جاري معالجة العملية...',
  'COMMUNICATING_WITH_BANK': 'جاري الاتصال بالبنك...',
  'RESPONSE_RECEIVED': 'تم استلام الرد من البنك',
  'REMOVE_CARD': 'الرجاء إزالة البطاقة',
  'CARD_REMOVED': 'تم إزالة البطاقة',
  'PRINTING_RECEIPT': 'جاري طباعة الإيصال...',
  'TRANSACTION_COMPLETE': 'تمت العملية',
  'TRANSACTION_FAILED': 'فشلت العملية',
  'REVERSAL_IN_PROGRESS': 'جاري إلغاء العملية...',
  'FALLBACK': 'جاري التبديل لقراءة أخرى',
};

/**
 * Format amount for POS: Remove decimals
 * 2.000 OMR → "2000"
 * 5.500 OMR → "5500"
 */
export const formatAmountForPOS = (amountInBaisas: number): string => {
  // Amount is already in baisas, just convert to string
  return Math.round(amountInBaisas).toString();
};

/**
 * Get error message for error code
 */
export const getErrorMessage = (errorCode: string): string => {
  const errorInfo = ECR_ERROR_CODES[errorCode] || getErrorInfo(errorCode);
  if (typeof errorInfo === 'object' && errorInfo.arabicMessage) {
    return errorInfo.arabicMessage;
  }
  return 'خطأ غير معروف';
};

/**
 * Get intermediate status message
 */
export const getIntermediateStatusMessage = (status: POSIntermediateStatus): string => {
  return INTERMEDIATE_STATUS_MESSAGES[status] || '';
};

/**
 * Initialize the POS connection with configuration
 */
export const initializePOS = async (config: POSConfig): Promise<boolean> => {
  try {
    currentConfig = { ...DEFAULT_CONFIG, ...config };
    setConnectionStatus('connecting');
    
    console.log('Initializing POS with config:', config);
    
    if (config.connectionType === 'usb') {
      return await initializeUSBConnection();
    } else if (config.connectionType === 'ethernet') {
      return await initializeEthernetConnection(config.ipAddress!, config.port!);
    }
    
    return false;
  } catch (error) {
    console.error('POS initialization error:', error);
    setConnectionStatus('error');
    return false;
  }
};

/**
 * Initialize USB connection
 * Uses Android USB Host / Serial APIs
 */
const initializeUSBConnection = async (): Promise<boolean> => {
  console.log('Initializing USB connection...');
  
  try {
    const deviceDetected = await detectUSBDevice();
    
    if (deviceDetected) {
      setConnectionStatus('connected');
      startConnectionMonitoring();
      return true;
    } else {
      setConnectionStatus('disconnected');
      return false;
    }
  } catch (error) {
    console.error('USB connection error:', error);
    setConnectionStatus('error');
    return false;
  }
};

/**
 * Detect USB POS device
 */
const detectUSBDevice = async (): Promise<boolean> => {
  console.log('Scanning for USB POS devices...');
  
  // Check for native Android USB bridge
  if (typeof (window as any).AndroidUSB !== 'undefined') {
    try {
      return await (window as any).AndroidUSB.detectDevice();
    } catch (e) {
      console.error('USB detection failed:', e);
      return false;
    }
  }
  
  // Check for OM-A880 specific bridge
  if (typeof (window as any).OMA880Bridge !== 'undefined') {
    try {
      const status = await (window as any).OMA880Bridge.getStatus();
      return status.connected;
    } catch (e) {
      console.error('OM-A880 bridge detection failed:', e);
      return false;
    }
  }
  
  // Web context - USB not available
  return false;
};

/**
 * Initialize Ethernet/TCP connection
 */
const initializeEthernetConnection = async (ipAddress: string, port: string): Promise<boolean> => {
  console.log(`Initializing Ethernet connection to ${ipAddress}:${port}...`);
  
  if (!ipAddress || !port) {
    console.error('IP address and port are required for Ethernet connection');
    setConnectionStatus('error');
    return false;
  }
  
  try {
    const connected = await validateEthernetConnection(ipAddress, port);
    
    if (connected) {
      setConnectionStatus('connected');
      startConnectionMonitoring();
      return true;
    } else {
      setConnectionStatus('disconnected');
      return false;
    }
  } catch (error) {
    console.error('Ethernet connection error:', error);
    setConnectionStatus('error');
    return false;
  }
};

/**
 * Validate Ethernet connection with timeout and retry logic
 */
const validateEthernetConnection = async (ipAddress: string, port: string): Promise<boolean> => {
  const timeout = currentConfig?.timeout || 5000;
  const retryAttempts = currentConfig?.retryAttempts || 3;
  
  for (let attempt = 1; attempt <= retryAttempts; attempt++) {
    console.log(`Connection attempt ${attempt}/${retryAttempts}...`);
    
    try {
      const connected = await attemptTCPConnection(ipAddress, port, timeout);
      
      if (connected) {
        console.log('Connection established successfully');
        return true;
      }
    } catch (error) {
      console.error(`Connection attempt ${attempt} failed:`, error);
    }
    
    if (attempt < retryAttempts) {
      await new Promise(resolve => setTimeout(resolve, 2000));
    }
  }
  
  return false;
};

/**
 * Attempt TCP connection
 */
const attemptTCPConnection = async (ipAddress: string, port: string, timeout: number): Promise<boolean> => {
  return new Promise((resolve) => {
    // Check for native TCP socket
    if (typeof (window as any).TCPSocket !== 'undefined') {
      const socket = (window as any).TCPSocket;
      socket.connect(ipAddress, parseInt(port), timeout)
        .then(() => resolve(true))
        .catch(() => resolve(false));
      return;
    }
    
    // Check for OM-A880 specific bridge
    if (typeof (window as any).OMA880Bridge !== 'undefined') {
      (window as any).OMA880Bridge.testConnection(ipAddress, port, timeout)
        .then((result: boolean) => resolve(result))
        .catch(() => resolve(false));
      return;
    }
    
    // Web context - TCP not directly available
    setTimeout(() => resolve(false), 1000);
  });
};

/**
 * Start connection monitoring
 */
const startConnectionMonitoring = () => {
  if (connectionCheckInterval) {
    clearInterval(connectionCheckInterval);
  }
  
  connectionCheckInterval = setInterval(async () => {
    if (connectionStatus === 'connected') {
      const stillConnected = await checkConnectionHealth();
      if (!stillConnected) {
        setConnectionStatus('disconnected');
      }
    }
  }, 5000);
};

/**
 * Check connection health
 */
const checkConnectionHealth = async (): Promise<boolean> => {
  if (!currentConfig) return false;
  
  if (currentConfig.connectionType === 'usb') {
    return await detectUSBDevice();
  } else {
    return await attemptTCPConnection(
      currentConfig.ipAddress!,
      currentConfig.port!,
      3000
    );
  }
};

/**
 * Set and notify connection status
 */
const setConnectionStatus = (status: ConnectionStatus) => {
  connectionStatus = status;
  statusListeners.forEach(listener => listener(status));
};

/**
 * Set and notify intermediate status
 */
const setIntermediateStatus = (status: POSIntermediateStatus) => {
  currentIntermediateStatus = status;
  const message = getIntermediateStatusMessage(status);
  intermediateStatusListeners.forEach(listener => listener(status, message));
};

/**
 * Get current connection status
 */
export const getConnectionStatus = (): ConnectionStatus => {
  return connectionStatus;
};

/**
 * Get current intermediate status
 */
export const getCurrentIntermediateStatus = (): POSIntermediateStatus | null => {
  return currentIntermediateStatus;
};

/**
 * Subscribe to connection status changes
 */
export const onConnectionStatusChange = (callback: StatusCallback): () => void => {
  statusListeners.push(callback);
  return () => {
    statusListeners = statusListeners.filter(cb => cb !== callback);
  };
};

/**
 * Subscribe to transaction responses
 */
export const onTransactionResponse = (callback: TransactionCallback): () => void => {
  transactionListeners.push(callback);
  return () => {
    transactionListeners = transactionListeners.filter(cb => cb !== callback);
  };
};

/**
 * Subscribe to intermediate status updates
 */
export const onIntermediateStatusChange = (callback: IntermediateStatusCallback): () => void => {
  intermediateStatusListeners.push(callback);
  return () => {
    intermediateStatusListeners = intermediateStatusListeners.filter(cb => cb !== callback);
  };
};

/**
 * Start a Purchase transaction (ECR Command)
 * 
 * When the donor confirms the donation amount:
 * - Send Purchase command to POS with amount and merchant reference
 * - If POS returns 1, command accepted (not transaction success)
 * - Listen for intermediate status messages
 * - Wait for final XML response
 */
export const startTransaction = async (request: TransactionRequest): Promise<TransactionResponse> => {
  if (connectionStatus !== 'connected') {
    return {
      success: false,
      transactionId: request.transactionId,
      errorCode: 'POS_NOT_CONNECTED',
      errorMessage: getErrorMessage('POS_NOT_CONNECTED'),
    };
  }
  
  transactionStatus = 'processing';
  currentIntermediateStatus = null;
  
  try {
    // Format amount: 2.000 OMR → "2000"
    const formattedAmount = formatAmountForPOS(request.amount);
    
    const message: POSMessage = {
      command: 'PURCHASE',
      payload: {
        amount: formattedAmount,
        transactionId: request.transactionId,
        merchantReference: request.merchantReference,
      },
    };
    
    console.log('Sending PURCHASE command to POS:', message);
    setIntermediateStatus('INITIALIZING');
    
    // Send transaction and wait for final response
    const response = await sendECRCommand(message);
    
    transactionStatus = response.success ? 'approved' : 'declined';
    
    // Notify listeners
    transactionListeners.forEach(listener => listener(response));
    
    return response;
  } catch (error: any) {
    transactionStatus = 'error';
    
    // On timeout, automatically check last transaction status
    if (error.message?.includes('TIMEOUT')) {
      console.log('Transaction timeout - checking last transaction status...');
      return await getLastTransactionStatus(request.transactionId);
    }
    
    const errorResponse: TransactionResponse = {
      success: false,
      transactionId: request.transactionId,
      errorCode: 'COMMUNICATION_FAILURE',
      errorMessage: error.message || getErrorMessage('COMMUNICATION_FAILURE'),
    };
    
    transactionListeners.forEach(listener => listener(errorResponse));
    
    return errorResponse;
  }
};

/**
 * Cancel current transaction (ECR Command)
 */
export const cancelTransaction = async (): Promise<boolean> => {
  if (transactionStatus !== 'processing') {
    return false;
  }
  
  try {
    const message: POSMessage = { command: 'CANCEL' };
    await sendECRCommand(message);
    transactionStatus = 'cancelled';
    return true;
  } catch (error) {
    console.error('Failed to cancel transaction:', error);
    return false;
  }
};

/**
 * Get POS Status (ECR Command)
 * Check POS readiness: printer, reader, connectivity
 */
export const getPOSStatus = async (): Promise<POSStatusResponse> => {
  try {
    const message: POSMessage = { command: 'GET_STATUS' };
    
    if (typeof (window as any).OMA880Bridge !== 'undefined') {
      const status = await (window as any).OMA880Bridge.getStatus();
      return {
        ready: status.ready,
        printerStatus: status.printer || 'ok',
        readerStatus: status.reader || 'ok',
        connectivity: status.online ? 'online' : 'offline',
        terminalId: status.tid,
        merchantId: status.mid,
      };
    }
    
    // Default response for simulation
    return {
      ready: connectionStatus === 'connected',
      printerStatus: 'ok',
      readerStatus: 'ok',
      connectivity: connectionStatus === 'connected' ? 'online' : 'offline',
    };
  } catch (error) {
    console.error('Failed to get POS status:', error);
    return {
      ready: false,
      printerStatus: 'error',
      readerStatus: 'error',
      connectivity: 'offline',
    };
  }
};

/**
 * Reconciliation - End of Day Settlement (ECR Command)
 */
export const performReconciliation = async (): Promise<ReconciliationResponse> => {
  try {
    const message: POSMessage = { command: 'RECONCILIATION' };
    
    if (typeof (window as any).OMA880Bridge !== 'undefined') {
      const result = await (window as any).OMA880Bridge.reconciliation();
      const resultCode = result.transactionResult || '0';
      const resultMap: Record<string, ReconciliationResponse['result']> = {
        '0': 'failed',
        '1': 'rejected',
        '2': 'accepted',
        '3': 'accepted_with_upload',
      };
      return {
        success: result.success,
        totalTransactions: result.count || 0,
        totalAmount: result.amount || 0,
        batchNumber: result.batchNo || '',
        timestamp: new Date().toISOString(),
        result: resultMap[resultCode] || 'failed',
      };
    }
    
    // Simulation response
    return {
      success: false,
      totalTransactions: 0,
      totalAmount: 0,
      batchNumber: '',
      timestamp: new Date().toISOString(),
      result: 'failed',
    };
  } catch (error) {
    console.error('Reconciliation failed:', error);
    throw error;
  }
};

/**
 * Get Transaction Totals (ECR Command)
 */
export const getTransactionTotals = async (): Promise<{ count: number; amount: number }> => {
  try {
    const message: POSMessage = { command: 'GET_TOTALS' };
    
    if (typeof (window as any).OMA880Bridge !== 'undefined') {
      const result = await (window as any).OMA880Bridge.getTotals();
      return {
        count: result.count || 0,
        amount: result.amount || 0,
      };
    }
    
    return { count: 0, amount: 0 };
  } catch (error) {
    console.error('Failed to get totals:', error);
    throw error;
  }
};

/**
 * Get Last Transaction Status (ECR Command)
 * Used when timeout occurs to check if transaction completed
 */
export const getLastTransactionStatus = async (transactionId: string): Promise<TransactionResponse> => {
  try {
    const message: POSMessage = { 
      command: 'LAST_TRANSACTION_STATUS',
      payload: { transactionId },
    };
    
    if (typeof (window as any).OMA880Bridge !== 'undefined') {
      const result = await (window as any).OMA880Bridge.lastTransactionStatus();
      return parseXMLResponse(result, transactionId);
    }
    
    return {
      success: false,
      transactionId,
      errorCode: 'POS_NOT_AVAILABLE',
      errorMessage: getErrorMessage('POS_NOT_AVAILABLE'),
    };
  } catch (error) {
    console.error('Failed to get last transaction status:', error);
    return {
      success: false,
      transactionId,
      errorCode: 'COMMUNICATION_FAILURE',
      errorMessage: getErrorMessage('COMMUNICATION_FAILURE'),
    };
  }
};

/**
 * Send ECR Command to POS and receive response
 */
const sendECRCommand = async (message: POSMessage): Promise<TransactionResponse> => {
  const timeout = currentConfig?.timeout || 120000;
  
  return new Promise((resolve, reject) => {
    const timeoutId = setTimeout(() => {
      reject(new Error('POS_TIMEOUT: Transaction timed out waiting for POS response'));
    }, timeout);
    
    // Check for OM-A880 native bridge
    if (typeof (window as any).OMA880Bridge !== 'undefined') {
      const bridge = (window as any).OMA880Bridge;
      
      // Set up intermediate status listener
      bridge.onStatusUpdate = (status: string) => {
        const mappedStatus = mapPOSStatus(status);
        if (mappedStatus) {
          setIntermediateStatus(mappedStatus);
        }
      };
      
      // Send command based on type
      let commandPromise: Promise<any>;
      
      switch (message.command) {
        case 'PURCHASE':
          commandPromise = bridge.purchase(
            message.payload?.amount,
            message.payload?.merchantReference
          );
          break;
        case 'CANCEL':
          commandPromise = bridge.cancel();
          break;
        default:
          commandPromise = bridge.sendCommand(message);
      }
      
      commandPromise
        .then((xmlResponse: any) => {
          clearTimeout(timeoutId);
          const response = parseXMLResponse(xmlResponse, message.payload?.transactionId || '');
          resolve(response);
        })
        .catch((error: any) => {
          clearTimeout(timeoutId);
          reject(error);
        });
      
      return;
    }
    
    // Simulation mode for development/testing
    clearTimeout(timeoutId);
    simulatePOSTransaction(message, resolve);
  });
};

/**
 * Map POS status string to typed status
 */
const mapPOSStatus = (status: string): POSIntermediateStatus | null => {
  const statusMap: Record<string, POSIntermediateStatus> = {
    'INSERT_CARD': 'INSERT_CARD',
    'TAP_CARD': 'TAP_CARD',
    'SWIPE_CARD': 'SWIPE_CARD',
    'ENTER_PIN': 'ENTER_PIN',
    'PROCESSING': 'PROCESSING',
    'COMMUNICATING': 'COMMUNICATING_WITH_BANK',
    'REMOVE_CARD': 'REMOVE_CARD',
    'PRINTING': 'PRINTING_RECEIPT',
    'COMPLETE': 'TRANSACTION_COMPLETE',
  };
  
  return statusMap[status.toUpperCase()] || null;
};

/**
 * Parse XML response from OM-A880 POS
 */
const parseXMLResponse = (xmlResponse: any, transactionId: string): TransactionResponse => {
  // Handle raw XML parsing if string
  if (typeof xmlResponse === 'string') {
    // Parse XML string (placeholder - use DOMParser in production)
    console.log('Parsing XML response:', xmlResponse);
  }
  
  // Map response to unified format
  const success = xmlResponse.responseCode === '00' || xmlResponse.approved === true;
  
  return {
    success,
    transactionId,
    posRRN: xmlResponse.rrn || xmlResponse.RRN,
    posAuthCode: xmlResponse.authCode || xmlResponse.AuthCode || xmlResponse.approvalCode,
    posTID: xmlResponse.tid || xmlResponse.TID || xmlResponse.terminalId,
    posMID: xmlResponse.mid || xmlResponse.MID || xmlResponse.merchantId,
    posResponseCode: xmlResponse.responseCode,
    cardLastFour: xmlResponse.cardLastFour || xmlResponse.pan?.slice(-4),
    cardType: xmlResponse.cardType || xmlResponse.scheme,
    receiptData: xmlResponse.receiptData || xmlResponse.receipt,
    errorCode: success ? undefined : xmlResponse.responseCode,
    errorMessage: success ? undefined : xmlResponse.responseMessage,
    rawResponse: xmlResponse,
  };
};

/**
 * Simulate POS transaction for development/testing
 */
const simulatePOSTransaction = (
  message: POSMessage, 
  resolve: (response: TransactionResponse) => void
) => {
  console.log('Simulating POS transaction...', message);
  
  // Simulate intermediate statuses
  const statuses: POSIntermediateStatus[] = [
    'INITIALIZING',
    'TAP_CARD',
    'PROCESSING',
    'COMMUNICATING_WITH_BANK',
    'TRANSACTION_COMPLETE',
  ];
  
  let statusIndex = 0;
  const statusInterval = setInterval(() => {
    if (statusIndex < statuses.length) {
      setIntermediateStatus(statuses[statusIndex]);
      statusIndex++;
    } else {
      clearInterval(statusInterval);
    }
  }, 800);
  
  // Simulate final response after 4 seconds
  setTimeout(() => {
    clearInterval(statusInterval);
    
    // Simulation: Always fail in web context without native bridge
    resolve({
      success: false,
      transactionId: message.payload?.transactionId || '',
      errorCode: 'POS_NOT_AVAILABLE',
      errorMessage: 'جهاز الدفع غير متوفر. يرجى توصيل جهاز OM-A880.',
    });
  }, 4000);
};

/**
 * Get current transaction status
 */
export const getTransactionStatus = (): TransactionStatus => {
  return transactionStatus;
};

/**
 * Reset transaction status to idle
 */
export const resetTransactionStatus = () => {
  transactionStatus = 'idle';
  currentIntermediateStatus = null;
};

/**
 * Disconnect from POS
 */
export const disconnectPOS = async (): Promise<void> => {
  if (connectionCheckInterval) {
    clearInterval(connectionCheckInterval);
    connectionCheckInterval = null;
  }
  
  setConnectionStatus('disconnected');
  currentConfig = null;
  
  console.log('POS disconnected');
};

/**
 * Test POS connection
 */
export const testConnection = async (config: POSConfig): Promise<{ connected: boolean; message: string; status?: POSStatusResponse }> => {
  try {
    // First try to connect
    if (config.connectionType === 'usb') {
      const detected = await detectUSBDevice();
      if (!detected) {
        return {
          connected: false,
          message: 'No USB POS device detected. Please connect the OM-A880 device.',
        };
      }
    } else {
      if (!config.ipAddress || !config.port) {
        return {
          connected: false,
          message: 'IP address and port are required for Ethernet connection',
        };
      }
      
      const connected = await attemptTCPConnection(config.ipAddress, config.port, 5000);
      if (!connected) {
        return {
          connected: false,
          message: `Unable to connect to ${config.ipAddress}:${config.port}. Please verify the IP and port settings.`,
        };
      }
    }
    
    // If connected, get POS status
    const tempConfig = currentConfig;
    currentConfig = config;
    const status = await getPOSStatus();
    currentConfig = tempConfig;
    
    if (!status.ready) {
      return {
        connected: true,
        message: 'POS connected but not ready. Please check printer and card reader.',
        status,
      };
    }
    
    return {
      connected: true,
      message: `POS connected successfully. TID: ${status.terminalId || 'N/A'}, MID: ${status.merchantId || 'N/A'}`,
      status,
    };
  } catch (error: any) {
    return {
      connected: false,
      message: error.message || 'Connection test failed',
    };
  }
};

/**
 * Receipt Strategy Configuration
 */
export type ReceiptStrategy = 'pos_prints' | 'kiosk_prints';

let receiptStrategy: ReceiptStrategy = 'pos_prints';

export const setReceiptStrategy = (strategy: ReceiptStrategy) => {
  receiptStrategy = strategy;
};

export const getReceiptStrategy = (): ReceiptStrategy => {
  return receiptStrategy;
};
