/**
 * OM-A880 Hardware POS Abstraction Layer (ECR Integration)
 * 
 * The KIOSK app acts as an ECR controller that sends transaction commands to the POS
 * and listens asynchronously for status updates and final transaction results.
 * 
 * All card reading, NFC, PIN entry, EMV processing, encryption, and bank communication
 * are handled entirely by the OM-A880 POS.
 * 
 * The KIOSK app must NOT process, store, or interpret card data.
 * 
 * Supported connection modes:
 * - Ethernet (TCP/IP): PRIMARY - Uses TCP socket with ECR protocol (RECOMMENDED)
 * - USB (Auto-detect): SECONDARY - Uses Android USB Host / Serial APIs
 * 
 * Compatible devices:
 * - Samsung Galaxy A13/A33 (trial phase)
 * - Sunmi Flex 3 (production)
 */

import {
  initializeUSBHost,
  isUSBHostAvailable,
  scanForDevices,
  connectToDevice,
  sendData as sendUSBData,
  disconnect as disconnectUSB,
  getConnectionState as getUSBConnectionState,
  getConnectedDevice,
  onConnectionStateChange as onUSBStateChange,
  onDataReceived as onUSBDataReceived,
  setKeepScreenAwake,
  USBDeviceInfo,
  DEFAULT_POS_IDENTIFIERS,
} from './usbHostService';

import {
  ECR_COMMANDS,
  INTERMEDIATE_MESSAGES,
  ERROR_CODES as ECR_ERROR_CODES,
  parseXMLResponse as parseECRXMLResponse,
  getErrorInfo,
  getIntermediateMessageInfo,
  isSuccessResponse,
  formatAmountForECR,
  ECRResponse,
} from './ecrProtocol';

// Import Ethernet ECR Service (PRIMARY connection method)
import {
  initializeEthernet,
  disconnectEthernet,
  sendCommand as sendEthernetCommand,
  buildPurchaseRequest,
  buildStatusRequest,
  buildTerminalInfoRequest,
  buildReconciliationRequest,
  buildLastTransactionRequest,
  buildTotalsRequest,
  getConnectionState as getEthernetState,
  onConnectionStateChange as onEthernetStateChange,
  onData as onEthernetData,
  testEthernetConnection,
  isEthernetAvailable,
  TCPConnectionState,
} from './ethernetEcrService';

// Import Web Serial Service (for Chrome/PWA USB communication)
import {
  isWebSerialAvailable,
  isWebSerialSupported,
  autoConnectToPOS as webSerialConnect,
  disconnect as webSerialDisconnect,
  sendCommand as webSerialSendCommand,
  getConnectionStatus as webSerialGetStatus,
  onConnectionChange as webSerialOnConnectionChange,
  onDataReceived as webSerialOnDataReceived,
} from './webSerialService';

// Import USB Bridge Service (for USB-to-TCP bridge apps)
import {
  initializeBridge,
  disconnectBridge,
  sendBridgeCommand,
  getBridgeState,
  onBridgeStateChange,
  onBridgeData,
  testBridgeConnection,
  getRecommendedApps,
} from './usbBridgeService';

// Connection types - added 'usbbridge' for USB bridge apps
export type ConnectionType = 'usb' | 'ethernet' | 'webserial' | 'usbbridge';

// POS Connection Status
export type ConnectionStatus = 'disconnected' | 'connecting' | 'connected' | 'ready' | 'error';

// Transaction Status (final states)
export type TransactionStatus = 'idle' | 'pending' | 'processing' | 'approved' | 'declined' | 'cancelled' | 'timeout' | 'error' | 'reversal_required';

// Intermediate POS Status Messages
export type POSIntermediateStatus = 
  | 'INITIALIZING'
  | 'INSERT_CARD'
  | 'TAP_CARD'
  | 'SWIPE_CARD'
  | 'ENTER_PIN'
  | 'PIN_ENTERED'
  | 'PROCESSING'
  | 'COMMUNICATING_WITH_BANK'
  | 'RESPONSE_RECEIVED'
  | 'REMOVE_CARD'
  | 'CARD_REMOVED'
  | 'PRINTING_RECEIPT'
  | 'TRANSACTION_COMPLETE'
  | 'TRANSACTION_FAILED'
  | 'REVERSAL_IN_PROGRESS'
  | 'FALLBACK';

// POS Configuration
export interface POSConfig {
  connectionType: ConnectionType;
  ipAddress?: string;
  port?: string;
  timeout?: number; // milliseconds
  retryAttempts?: number;
  // USB specific configuration
  vendorId?: number;
  productId?: number;
  autoDetect?: boolean;
  // USB Bridge configuration
  bridgeHost?: string; // localhost for bridge apps
  bridgePort?: number; // typically 8888
}

// Transaction Request
export interface TransactionRequest {
  transactionId: string;
  amount: number; // in baisas - will be formatted as integer without decimals
  merchantReference?: string; // optional donation ID (max 22 chars)
  currency?: string;
}

// POS XML Response (from OM-A880)
export interface POSXMLResponse {
  success: boolean;
  responseCode: string;
  responseMessage: string;
  transactionAmount: string;
  rrn: string; // Bank Transaction Reference (RRN)
  authCode: string; // Authorization Code
  tid: string; // Terminal ID
  mid: string; // Merchant ID
  cardLastFour?: string;
  cardType?: string;
  receiptData?: string; // Raw receipt data for printing
  rawXML?: string; // Original XML for debugging
  batchNo?: string;
  invoiceNo?: string;
  sequenceNo?: string;
  entryMode?: string;
  txnStatus?: string;
}

// Transaction Response (unified format for app)
export interface TransactionResponse {
  success: boolean;
  transactionId: string;
  // System reference (generated by app - remains unchanged)
  systemReference?: string;
  // POS/Bank references
  posRRN?: string; // Bank Transaction Reference
  posAuthCode?: string; // Authorization Code
  posTID?: string; // Terminal ID
  posMID?: string; // Merchant ID
  posResponseCode?: string;
  // Card info (for display only - no storing sensitive data)
  cardLastFour?: string;
  cardType?: string;
  // Receipt
  receiptData?: string;
  // Error handling
  errorCode?: string;
  errorMessage?: string;
  rawResponse?: POSXMLResponse;
}

// ECR Command Types
export type ECRCommand = 
  | 'PURCHASE'
  | 'REFUND'
  | 'VOID'
  | 'CANCEL'
  | 'GET_STATUS'
  | 'RECONCILIATION'
  | 'GET_TOTALS'
  | 'GET_TERMINAL_INFO'
  | 'LAST_TRANSACTION_STATUS'
  | 'DELETE_BATCH'
  | 'DELETE_REVERSAL';

// POS Message Protocol
export interface POSMessage {
  command: ECRCommand;
  payload?: {
    amount?: string; // Integer string without decimals: 2.000 OMR → "2000"
    transactionId?: string;
    merchantReference?: string;
    invoiceNumber?: string;
  };
}

// POS Status Response
export interface POSStatusResponse {
  ready: boolean;
  printerStatus: 'ok' | 'paper_out' | 'error';
  readerStatus: 'ok' | 'card_present' | 'error';
  connectivity: 'online' | 'offline';
  terminalId?: string;
  merchantId?: string;
  appVersion?: string;
  serialNo?: string;
  batchNo?: string;
}

// Reconciliation Response
export interface ReconciliationResponse {
  success: boolean;
  totalTransactions: number;
  totalAmount: number;
  batchNumber: string;
  timestamp: string;
  result: 'failed' | 'rejected' | 'accepted' | 'accepted_with_upload';
}

// Event callbacks
type StatusCallback = (status: ConnectionStatus) => void;
type TransactionCallback = (response: TransactionResponse) => void;
type IntermediateStatusCallback = (status: POSIntermediateStatus, message: string) => void;

// Internal state
let currentConfig: POSConfig | null = null;
let connectionStatus: ConnectionStatus = 'disconnected';
let transactionStatus: TransactionStatus = 'idle';
let currentIntermediateStatus: POSIntermediateStatus | null = null;
let statusListeners: StatusCallback[] = [];
let transactionListeners: TransactionCallback[] = [];
let intermediateStatusListeners: IntermediateStatusCallback[] = [];
let connectionCheckInterval: ReturnType<typeof setInterval> | null = null;
let lastHandshakeTime: number | null = null;
let lastErrorMessage: string | null = null;

// Default configuration
const DEFAULT_CONFIG: Partial<POSConfig> = {
  timeout: 120000, // 2 minutes for POS transactions
  retryAttempts: 3,
  autoDetect: true,
};

// Intermediate status messages (Arabic) - mapped from ECR protocol codes
const INTERMEDIATE_STATUS_MESSAGES: Record<POSIntermediateStatus, string> = {
  'INITIALIZING': 'جاري التهيئة...',
  'INSERT_CARD': 'الرجاء إدخال البطاقة',
  'TAP_CARD': 'الرجاء تقريب البطاقة',
  'SWIPE_CARD': 'الرجاء تمرير البطاقة',
  'ENTER_PIN': 'الرجاء إدخال الرقم السري',
  'PIN_ENTERED': 'تم إدخال الرقم السري',
  'PROCESSING': 'جاري معالجة العملية...',
  'COMMUNICATING_WITH_BANK': 'جاري الاتصال بالبنك...',
  'RESPONSE_RECEIVED': 'تم استلام الرد من البنك',
  'REMOVE_CARD': 'الرجاء إزالة البطاقة',
  'CARD_REMOVED': 'تم إزالة البطاقة',
  'PRINTING_RECEIPT': 'جاري طباعة الإيصال...',
  'TRANSACTION_COMPLETE': 'تمت العملية',
  'TRANSACTION_FAILED': 'فشلت العملية',
  'REVERSAL_IN_PROGRESS': 'جاري إلغاء العملية...',
  'FALLBACK': 'جاري التبديل لقراءة أخرى',
};

/**
 * Format amount for POS: Remove decimals
 * 2.000 OMR → "2000"
 * 5.500 OMR → "5500"
 */
export const formatAmountForPOS = (amountInBaisas: number): string => {
  // Amount is already in baisas, just convert to string
  return Math.round(amountInBaisas).toString();
};

/**
 * Get error message for error code
 */
export const getErrorMessage = (errorCode: string): string => {
  const errorInfo = ECR_ERROR_CODES[errorCode] || getErrorInfo(errorCode);
  if (typeof errorInfo === 'object' && errorInfo.arabicMessage) {
    return errorInfo.arabicMessage;
  }
  return 'خطأ غير معروف';
};

/**
 * Get intermediate status message
 */
export const getIntermediateStatusMessage = (status: POSIntermediateStatus): string => {
  return INTERMEDIATE_STATUS_MESSAGES[status] || '';
};

/**
 * Initialize the POS connection with configuration
 * PRIORITY: USB Bridge > Ethernet (TCP/IP) > USB Native
 */
export const initializePOS = async (config: POSConfig): Promise<boolean> => {
  try {
    currentConfig = { ...DEFAULT_CONFIG, ...config };
    setConnectionStatus('connecting');
    
    console.log('Initializing POS with config:', config);
    console.log('Connection type:', config.connectionType);
    
    // USB BRIDGE is now the RECOMMENDED method for Android
    if (config.connectionType === 'usbbridge') {
      console.log('Using USB Bridge connection (recommended for Android)');
      return await initializeUSBBridgeConnection(
        config.bridgeHost || '127.0.0.1',
        config.bridgePort || 8888
      );
    }
    
    // ETHERNET for direct TCP/IP connection
    if (config.connectionType === 'ethernet') {
      return await initializeEthernetConnection(config.ipAddress!, config.port!);
    }
    
    // WEB SERIAL for Chrome/PWA - uses browser's Web Serial API (desktop only)
    if (config.connectionType === 'webserial') {
      console.log('Using Web Serial connection (Chrome desktop only)');
      return await initializeWebSerialConnection();
    }
    
    // USB NATIVE (requires Capacitor native plugin)
    if (config.connectionType === 'usb') {
      console.log('Using USB connection (native method)');
      return await initializeUSBConnection();
    }
    
    // Default: Try USB Bridge first (for Android), then Ethernet
    console.log('Auto-detecting best connection method...');
    
    // Try USB Bridge (most compatible with Android + USB bridge apps)
    const bridgeConnected = await initializeUSBBridgeConnection(
      config.bridgeHost || '127.0.0.1',
      config.bridgePort || 8888
    );
    if (bridgeConnected) {
      return true;
    }
    
    // Try Ethernet if configured
    if (config.ipAddress && config.port) {
      console.log('Trying Ethernet connection');
      return await initializeEthernetConnection(config.ipAddress, config.port);
    }
    
    setConnectionStatus('disconnected');
    lastErrorMessage = 'No connection method available. Please configure USB Bridge or Ethernet.';
    return false;
  } catch (error) {
    console.error('POS initialization error:', error);
    setConnectionStatus('error');
    return false;
  }
};

/**
 * Initialize USB Bridge connection
 * Uses a USB-to-TCP bridge app (like Serial USB Terminal) on Android
 */
const initializeUSBBridgeConnection = async (host: string, port: number): Promise<boolean> => {
  console.log(`[USBBridge] Initializing connection to ${host}:${port}...`);
  
  try {
    // Subscribe to state changes
    onBridgeStateChange((state) => {
      console.log('[USBBridge] State changed:', state);
      if (state === 'connected') {
        setConnectionStatus('connected');
      } else if (state === 'disconnected' || state === 'error') {
        setConnectionStatus(state === 'error' ? 'error' : 'disconnected');
      }
    });
    
    // Subscribe to incoming data
    onBridgeData((data) => {
      handleIncomingPOSData(data);
    });
    
    const connected = await initializeBridge({ host, port, timeout: currentConfig?.timeout || 120000 });
    
    if (connected) {
      setConnectionStatus('connected');
      startConnectionMonitoring();
      return true;
    }
    
    return false;
  } catch (error: any) {
    console.error('[USBBridge] Connection error:', error);
    lastErrorMessage = error.message || 'USB Bridge connection failed';
    setConnectionStatus('error');
    return false;
  }
};

/**
 * Initialize Web Serial connection (Chrome/PWA)
 * Uses browser's Web Serial API - no native plugins required
 */
const initializeWebSerialConnection = async (): Promise<boolean> => {
  console.log('Initializing Web Serial connection (Chrome/PWA)...');
  
  const support = isWebSerialSupported();
  if (!support.supported) {
    console.error('Web Serial not supported:', support.reason);
    lastErrorMessage = support.reason || 'Web Serial not supported';
    setConnectionStatus('error');
    return false;
  }
  
  try {
    // Subscribe to connection changes
    webSerialOnConnectionChange((connected) => {
      console.log('Web Serial connection changed:', connected);
      setConnectionStatus(connected ? 'connected' : 'disconnected');
    });
    
    // Subscribe to incoming data for intermediate status
    webSerialOnDataReceived((data) => {
      handleIncomingPOSData(data);
    });
    
    // Connect to POS via Web Serial (will prompt user to select device)
    const result = await webSerialConnect();
    
    if (result.connected) {
      setConnectionStatus('connected');
      startConnectionMonitoring();
      return true;
    } else {
      lastErrorMessage = result.error || 'Failed to connect via Web Serial';
      setConnectionStatus('disconnected');
      return false;
    }
  } catch (error: any) {
    console.error('Web Serial connection error:', error);
    lastErrorMessage = error.message || 'Web Serial connection failed';
    setConnectionStatus('error');
    return false;
  }
};

/**
 * Initialize USB connection (native Capacitor method)
 * Uses Android USB Host / Serial APIs - requires native plugin
 */
const initializeUSBConnection = async (): Promise<boolean> => {
  console.log('Initializing USB connection (native method)...');
  
  try {
    const deviceDetected = await detectUSBDevice();
    
    if (deviceDetected) {
      setConnectionStatus('connected');
      startConnectionMonitoring();
      return true;
    } else {
      setConnectionStatus('disconnected');
      return false;
    }
  } catch (error) {
    console.error('USB connection error:', error);
    setConnectionStatus('error');
    return false;
  }
};

/**
 * Detect USB POS device
 */
const detectUSBDevice = async (): Promise<boolean> => {
  console.log('Scanning for USB POS devices...');
  
  // Check for native Android USB bridge
  if (typeof (window as any).AndroidUSB !== 'undefined') {
    try {
      return await (window as any).AndroidUSB.detectDevice();
    } catch (e) {
      console.error('USB detection failed:', e);
      return false;
    }
  }
  
  // Check for OM-A880 specific bridge
  if (typeof (window as any).OMA880Bridge !== 'undefined') {
    try {
      const status = await (window as any).OMA880Bridge.getStatus();
      return status.connected;
    } catch (e) {
      console.error('OM-A880 bridge detection failed:', e);
      return false;
    }
  }
  
  // Web context - USB not available
  return false;
};

/**
 * Initialize Ethernet/TCP connection (PRIMARY method)
 * Uses the ethernetEcrService for proper ECR protocol communication
 */
const initializeEthernetConnection = async (ipAddress: string, port: string): Promise<boolean> => {
  console.log(`Initializing Ethernet ECR connection to ${ipAddress}:${port}...`);
  
  if (!ipAddress || !port) {
    console.error('IP address and port are required for Ethernet connection');
    setConnectionStatus('error');
    lastErrorMessage = 'IP address and port are required';
    return false;
  }
  
  try {
    // Use the dedicated Ethernet ECR service
    const connected = await initializeEthernet({
      ipAddress,
      port: parseInt(port),
      timeout: currentConfig?.timeout || 120000,
      retryAttempts: currentConfig?.retryAttempts || 3,
      keepAliveInterval: 30000,
    });
    
    if (connected) {
      setConnectionStatus('connected');
      
      // Subscribe to Ethernet state changes
      onEthernetStateChange((state) => {
        console.log('Ethernet state changed:', state);
        if (state === 'disconnected' || state === 'error') {
          setConnectionStatus(state === 'error' ? 'error' : 'disconnected');
        }
      });
      
      // Subscribe to incoming data for intermediate status
      onEthernetData((data) => {
        handleIncomingPOSData(data);
      });
      
      // Verify connection with terminal info request
      try {
        const infoXml = buildTerminalInfoRequest();
        const terminalInfo = await sendEthernetCommand(infoXml, 10000);
        
        if (terminalInfo) {
          console.log('Terminal connected:', {
            tid: terminalInfo.tid,
            mid: terminalInfo.mid,
            errorCode: terminalInfo.errorCode,
          });
          setConnectionStatus('ready');
        }
      } catch (infoError) {
        console.warn('Could not get terminal info, but connection established');
      }
      
      startConnectionMonitoring();
      return true;
    } else {
      setConnectionStatus('disconnected');
      lastErrorMessage = `Unable to connect to ${ipAddress}:${port}`;
      return false;
    }
  } catch (error: any) {
    console.error('Ethernet connection error:', error);
    setConnectionStatus('error');
    lastErrorMessage = error.message || 'Ethernet connection failed';
    return false;
  }
};

/**
 * Handle incoming data from POS (for intermediate status messages)
 */
const handleIncomingPOSData = (data: string) => {
  console.log('Incoming POS data:', data.substring(0, 200));
  
  // Check for intermediate status messages
  if (data.includes('<IntermediateStatus>') || data.includes('<StatusCode>')) {
    const statusMatch = data.match(/<StatusCode>(\d+)<\/StatusCode>/);
    if (statusMatch) {
      const statusCode = statusMatch[1];
      const statusInfo = INTERMEDIATE_MESSAGES[statusCode];
      
      if (statusInfo) {
        const mappedStatus = mapIntermediateCode(statusCode);
        if (mappedStatus) {
          setIntermediateStatus(mappedStatus);
        }
      }
    }
  }
};

/**
 * Map ECR intermediate status code to app status
 */
const mapIntermediateCode = (code: string): POSIntermediateStatus | null => {
  const codeMap: Record<string, POSIntermediateStatus> = {
    '001': 'INSERT_CARD',
    '002': 'INSERT_CARD', // Card inserted
    '003': 'FALLBACK',
    '005': 'SWIPE_CARD',
    '006': 'ENTER_PIN',
    '007': 'PIN_ENTERED',
    '008': 'COMMUNICATING_WITH_BANK',
    '009': 'RESPONSE_RECEIVED',
    '010': 'PRINTING_RECEIPT',
    '011': 'REMOVE_CARD',
    '012': 'CARD_REMOVED',
    '013': 'TRANSACTION_COMPLETE',
    '014': 'TRANSACTION_FAILED',
    '015': 'REVERSAL_IN_PROGRESS',
    '018': 'TRANSACTION_COMPLETE',
  };
  
  return codeMap[code] || null;
};

/**
 * Attempt TCP connection
 */
const attemptTCPConnection = async (ipAddress: string, port: string, timeout: number): Promise<boolean> => {
  return new Promise((resolve) => {
    // Check for native TCP socket
    if (typeof (window as any).TCPSocket !== 'undefined') {
      const socket = (window as any).TCPSocket;
      socket.connect(ipAddress, parseInt(port), timeout)
        .then(() => resolve(true))
        .catch(() => resolve(false));
      return;
    }
    
    // Check for OM-A880 specific bridge
    if (typeof (window as any).OMA880Bridge !== 'undefined') {
      (window as any).OMA880Bridge.testConnection(ipAddress, port, timeout)
        .then((result: boolean) => resolve(result))
        .catch(() => resolve(false));
      return;
    }
    
    // Web context - TCP not directly available
    setTimeout(() => resolve(false), 1000);
  });
};

/**
 * Start connection monitoring
 */
const startConnectionMonitoring = () => {
  if (connectionCheckInterval) {
    clearInterval(connectionCheckInterval);
  }
  
  connectionCheckInterval = setInterval(async () => {
    if (connectionStatus === 'connected') {
      const stillConnected = await checkConnectionHealth();
      if (!stillConnected) {
        setConnectionStatus('disconnected');
      }
    }
  }, 5000);
};

/**
 * Check connection health
 */
const checkConnectionHealth = async (): Promise<boolean> => {
  if (!currentConfig) return false;
  
  if (currentConfig.connectionType === 'usb') {
    return await detectUSBDevice();
  } else {
    return await attemptTCPConnection(
      currentConfig.ipAddress!,
      currentConfig.port!,
      3000
    );
  }
};

/**
 * Set and notify connection status
 */
const setConnectionStatus = (status: ConnectionStatus) => {
  connectionStatus = status;
  statusListeners.forEach(listener => listener(status));
};

/**
 * Set and notify intermediate status
 */
const setIntermediateStatus = (status: POSIntermediateStatus) => {
  currentIntermediateStatus = status;
  const message = getIntermediateStatusMessage(status);
  intermediateStatusListeners.forEach(listener => listener(status, message));
};

/**
 * Get current connection status
 */
export const getConnectionStatus = (): ConnectionStatus => {
  return connectionStatus;
};

/**
 * Get current intermediate status
 */
export const getCurrentIntermediateStatus = (): POSIntermediateStatus | null => {
  return currentIntermediateStatus;
};

/**
 * Subscribe to connection status changes
 */
export const onConnectionStatusChange = (callback: StatusCallback): () => void => {
  statusListeners.push(callback);
  return () => {
    statusListeners = statusListeners.filter(cb => cb !== callback);
  };
};

/**
 * Subscribe to transaction responses
 */
export const onTransactionResponse = (callback: TransactionCallback): () => void => {
  transactionListeners.push(callback);
  return () => {
    transactionListeners = transactionListeners.filter(cb => cb !== callback);
  };
};

/**
 * Subscribe to intermediate status updates
 */
export const onIntermediateStatusChange = (callback: IntermediateStatusCallback): () => void => {
  intermediateStatusListeners.push(callback);
  return () => {
    intermediateStatusListeners = intermediateStatusListeners.filter(cb => cb !== callback);
  };
};

/**
 * Start a Purchase transaction (ECR Command)
 * 
 * When the donor confirms the donation amount:
 * - Send Purchase command to POS with amount and merchant reference
 * - If POS returns 1, command accepted (not transaction success)
 * - Listen for intermediate status messages
 * - Wait for final XML response
 */
export const startTransaction = async (request: TransactionRequest): Promise<TransactionResponse> => {
  if (connectionStatus !== 'connected') {
    return {
      success: false,
      transactionId: request.transactionId,
      errorCode: 'POS_NOT_CONNECTED',
      errorMessage: getErrorMessage('POS_NOT_CONNECTED'),
    };
  }
  
  transactionStatus = 'processing';
  currentIntermediateStatus = null;
  
  try {
    // Format amount: 2.000 OMR → "2000"
    const formattedAmount = formatAmountForPOS(request.amount);
    
    const message: POSMessage = {
      command: 'PURCHASE',
      payload: {
        amount: formattedAmount,
        transactionId: request.transactionId,
        merchantReference: request.merchantReference,
      },
    };
    
    console.log('Sending PURCHASE command to POS:', message);
    setIntermediateStatus('INITIALIZING');
    
    // Send transaction and wait for final response
    const response = await sendECRCommand(message);
    
    transactionStatus = response.success ? 'approved' : 'declined';
    
    // Notify listeners
    transactionListeners.forEach(listener => listener(response));
    
    return response;
  } catch (error: any) {
    transactionStatus = 'error';
    
    // On timeout, automatically check last transaction status
    if (error.message?.includes('TIMEOUT')) {
      console.log('Transaction timeout - checking last transaction status...');
      return await getLastTransactionStatus(request.transactionId);
    }
    
    const errorResponse: TransactionResponse = {
      success: false,
      transactionId: request.transactionId,
      errorCode: 'COMMUNICATION_FAILURE',
      errorMessage: error.message || getErrorMessage('COMMUNICATION_FAILURE'),
    };
    
    transactionListeners.forEach(listener => listener(errorResponse));
    
    return errorResponse;
  }
};

/**
 * Cancel current transaction (ECR Command)
 */
export const cancelTransaction = async (): Promise<boolean> => {
  if (transactionStatus !== 'processing') {
    return false;
  }
  
  try {
    const message: POSMessage = { command: 'CANCEL' };
    await sendECRCommand(message);
    transactionStatus = 'cancelled';
    return true;
  } catch (error) {
    console.error('Failed to cancel transaction:', error);
    return false;
  }
};

/**
 * Get POS Status (ECR Command)
 * Check POS readiness: printer, reader, connectivity
 */
export const getPOSStatus = async (): Promise<POSStatusResponse> => {
  try {
    const message: POSMessage = { command: 'GET_STATUS' };
    
    if (typeof (window as any).OMA880Bridge !== 'undefined') {
      const status = await (window as any).OMA880Bridge.getStatus();
      return {
        ready: status.ready,
        printerStatus: status.printer || 'ok',
        readerStatus: status.reader || 'ok',
        connectivity: status.online ? 'online' : 'offline',
        terminalId: status.tid,
        merchantId: status.mid,
      };
    }
    
    // Default response for simulation
    return {
      ready: connectionStatus === 'connected',
      printerStatus: 'ok',
      readerStatus: 'ok',
      connectivity: connectionStatus === 'connected' ? 'online' : 'offline',
    };
  } catch (error) {
    console.error('Failed to get POS status:', error);
    return {
      ready: false,
      printerStatus: 'error',
      readerStatus: 'error',
      connectivity: 'offline',
    };
  }
};

/**
 * Reconciliation - End of Day Settlement (ECR Command)
 */
export const performReconciliation = async (): Promise<ReconciliationResponse> => {
  try {
    const message: POSMessage = { command: 'RECONCILIATION' };
    
    if (typeof (window as any).OMA880Bridge !== 'undefined') {
      const result = await (window as any).OMA880Bridge.reconciliation();
      const resultCode = result.transactionResult || '0';
      const resultMap: Record<string, ReconciliationResponse['result']> = {
        '0': 'failed',
        '1': 'rejected',
        '2': 'accepted',
        '3': 'accepted_with_upload',
      };
      return {
        success: result.success,
        totalTransactions: result.count || 0,
        totalAmount: result.amount || 0,
        batchNumber: result.batchNo || '',
        timestamp: new Date().toISOString(),
        result: resultMap[resultCode] || 'failed',
      };
    }
    
    // Simulation response
    return {
      success: false,
      totalTransactions: 0,
      totalAmount: 0,
      batchNumber: '',
      timestamp: new Date().toISOString(),
      result: 'failed',
    };
  } catch (error) {
    console.error('Reconciliation failed:', error);
    throw error;
  }
};

/**
 * Get Transaction Totals (ECR Command)
 */
export const getTransactionTotals = async (): Promise<{ count: number; amount: number }> => {
  try {
    const message: POSMessage = { command: 'GET_TOTALS' };
    
    if (typeof (window as any).OMA880Bridge !== 'undefined') {
      const result = await (window as any).OMA880Bridge.getTotals();
      return {
        count: result.count || 0,
        amount: result.amount || 0,
      };
    }
    
    return { count: 0, amount: 0 };
  } catch (error) {
    console.error('Failed to get totals:', error);
    throw error;
  }
};

/**
 * Get Last Transaction Status (ECR Command)
 * Used when timeout occurs to check if transaction completed
 */
export const getLastTransactionStatus = async (transactionId: string): Promise<TransactionResponse> => {
  try {
    const message: POSMessage = { 
      command: 'LAST_TRANSACTION_STATUS',
      payload: { transactionId },
    };
    
    if (typeof (window as any).OMA880Bridge !== 'undefined') {
      const result = await (window as any).OMA880Bridge.lastTransactionStatus();
      return parseXMLResponse(result, transactionId);
    }
    
    return {
      success: false,
      transactionId,
      errorCode: 'POS_NOT_AVAILABLE',
      errorMessage: getErrorMessage('POS_NOT_AVAILABLE'),
    };
  } catch (error) {
    console.error('Failed to get last transaction status:', error);
    return {
      success: false,
      transactionId,
      errorCode: 'COMMUNICATION_FAILURE',
      errorMessage: getErrorMessage('COMMUNICATION_FAILURE'),
    };
  }
};

/**
 * Send ECR Command to POS and receive response
 * PRIORITY: Web Serial (Chrome/PWA) > Ethernet (TCP/IP) > Native Bridge > USB
 */
const sendECRCommand = async (message: POSMessage): Promise<TransactionResponse> => {
  const timeout = currentConfig?.timeout || 120000;
  
  // WEB SERIAL for Chrome/PWA (no native plugins required)
  if (currentConfig?.connectionType === 'webserial' && webSerialGetStatus()) {
    console.log('Sending ECR command via Web Serial:', message.command);
    return await sendECRViaWebSerial(message, timeout);
  }
  
  // ETHERNET is the PRIMARY method for native apps
  if (currentConfig?.connectionType === 'ethernet' && getEthernetState() === 'connected') {
    console.log('Sending ECR command via Ethernet:', message.command);
    return await sendECRViaEthernet(message, timeout);
  }
  
  // Fall back to native bridge if available
  if (typeof (window as any).OMA880Bridge !== 'undefined') {
    console.log('Sending ECR command via Native Bridge:', message.command);
    return await sendECRViaNativeBridge(message, timeout);
  }
  
  // Fall back to USB if configured (requires native plugin)
  if (currentConfig?.connectionType === 'usb') {
    console.log('Sending ECR command via USB:', message.command);
    return await sendECRViaUSB(message, timeout);
  }
  
  // Simulation mode for development/testing
  console.log('No POS connection - entering simulation mode');
  return new Promise((resolve) => {
    simulatePOSTransaction(message, resolve);
  });
};

/**
 * Send ECR command via Web Serial (Chrome/PWA) - NO NATIVE PLUGINS REQUIRED
 */
const sendECRViaWebSerial = async (message: POSMessage, timeout: number): Promise<TransactionResponse> => {
  let xmlRequest: string;
  
  switch (message.command) {
    case 'PURCHASE':
      xmlRequest = buildPurchaseRequest(
        parseInt(message.payload?.amount || '0'),
        message.payload?.invoiceNumber,
        message.payload?.merchantReference
      );
      break;
    case 'GET_STATUS':
      xmlRequest = buildStatusRequest();
      break;
    case 'GET_TERMINAL_INFO':
      xmlRequest = buildTerminalInfoRequest();
      break;
    case 'RECONCILIATION':
      xmlRequest = buildReconciliationRequest();
      break;
    case 'LAST_TRANSACTION_STATUS':
      xmlRequest = buildLastTransactionRequest();
      break;
    case 'GET_TOTALS':
      xmlRequest = buildTotalsRequest();
      break;
    default:
      xmlRequest = `<?xml version="1.0" encoding="UTF-8"?><ECRMessage><CommandType>${ECR_COMMANDS[message.command] || message.command}</CommandType></ECRMessage>`;
  }
  
  try {
    const responseXml = await webSerialSendCommand(xmlRequest, timeout);
    
    if (!responseXml) {
      throw new Error('No response from POS');
    }
    
    // Parse the XML response
    const ecrResponse = parseECRXMLResponse(responseXml);
    
    // Convert ECRResponse to TransactionResponse
    return convertECRToTransactionResponse(ecrResponse, message.payload?.transactionId || '');
  } catch (error: any) {
    console.error('Web Serial ECR command failed:', error);
    throw error;
  }
};

/**
 * Send ECR command via Ethernet (TCP/IP) - PRIMARY METHOD
 */
const sendECRViaEthernet = async (message: POSMessage, timeout: number): Promise<TransactionResponse> => {
  let xmlRequest: string;
  
  switch (message.command) {
    case 'PURCHASE':
      xmlRequest = buildPurchaseRequest(
        parseInt(message.payload?.amount || '0'),
        message.payload?.invoiceNumber,
        message.payload?.merchantReference
      );
      break;
    case 'GET_STATUS':
      xmlRequest = buildStatusRequest();
      break;
    case 'GET_TERMINAL_INFO':
      xmlRequest = buildTerminalInfoRequest();
      break;
    case 'RECONCILIATION':
      xmlRequest = buildReconciliationRequest();
      break;
    case 'LAST_TRANSACTION_STATUS':
      xmlRequest = buildLastTransactionRequest();
      break;
    case 'GET_TOTALS':
      xmlRequest = buildTotalsRequest();
      break;
    default:
      // Build generic request
      xmlRequest = `<?xml version="1.0" encoding="UTF-8"?><ECRMessage><CommandType>${ECR_COMMANDS[message.command] || message.command}</CommandType></ECRMessage>`;
  }
  
  try {
    const ecrResponse = await sendEthernetCommand(xmlRequest, timeout);
    
    if (!ecrResponse) {
      throw new Error('No response from POS');
    }
    
    // Convert ECRResponse to TransactionResponse
    return convertECRToTransactionResponse(ecrResponse, message.payload?.transactionId || '');
  } catch (error: any) {
    console.error('Ethernet ECR command failed:', error);
    throw error;
  }
};

/**
 * Convert ECRResponse to TransactionResponse
 */
const convertECRToTransactionResponse = (ecr: ECRResponse, transactionId: string): TransactionResponse => {
  // Success if responseCode is '00' or hostRspCode is '00' and errorCode is 'E000'
  const success = (
    ecr.responseCode === '00' || 
    ecr.hostRspCode === '00' ||
    (ecr.errorCode === 'E000' && ecr.txnStatus === 'OK')
  );
  
  return {
    success,
    transactionId,
    posRRN: ecr.rrn,
    posAuthCode: ecr.authCode,
    posTID: ecr.tid,
    posMID: ecr.mid,
    posResponseCode: ecr.responseCode || ecr.hostRspCode,
    cardLastFour: ecr.maskCardNumber?.slice(-4),
    cardType: ecr.cardSchemeName,
    receiptData: ecr.receiptDataCustomer || ecr.receiptDataMerchant,
    errorCode: success ? undefined : ecr.errorCode,
    errorMessage: success ? undefined : (ecr.responseDesc || getErrorMessage(ecr.errorCode)),
    rawResponse: ecr as any,
  };
};

/**
 * Send ECR command via Native Bridge (Android)
 */
const sendECRViaNativeBridge = async (message: POSMessage, timeout: number): Promise<TransactionResponse> => {
  return new Promise((resolve, reject) => {
    const timeoutId = setTimeout(() => {
      reject(new Error('POS_TIMEOUT: Transaction timed out waiting for POS response'));
    }, timeout);
    
    const bridge = (window as any).OMA880Bridge;
    
    // Set up intermediate status listener
    bridge.onStatusUpdate = (status: string) => {
      const mappedStatus = mapPOSStatus(status);
      if (mappedStatus) {
        setIntermediateStatus(mappedStatus);
      }
    };
    
    // Send command based on type
    let commandPromise: Promise<any>;
    
    switch (message.command) {
      case 'PURCHASE':
        commandPromise = bridge.purchase(
          message.payload?.amount,
          message.payload?.merchantReference
        );
        break;
      case 'CANCEL':
        commandPromise = bridge.cancel();
        break;
      default:
        commandPromise = bridge.sendCommand(message);
    }
    
    commandPromise
      .then((xmlResponse: any) => {
        clearTimeout(timeoutId);
        const response = parseXMLResponse(xmlResponse, message.payload?.transactionId || '');
        resolve(response);
      })
      .catch((error: any) => {
        clearTimeout(timeoutId);
        reject(error);
      });
  });
};

/**
 * Send ECR command via USB Serial (using capacitor-plugin-usb-serial)
 */
const sendECRViaUSB = async (message: POSMessage, timeout: number): Promise<TransactionResponse> => {
  // Import the USB serial plugin functions
  const { writeUSBData, readUSBData, isUSBConnected, onDataReceived } = await import('./usbSerialPlugin');
  
  return new Promise(async (resolve, reject) => {
    const timeoutId = setTimeout(() => {
      reject(new Error('POS_TIMEOUT: Transaction timed out waiting for USB POS response'));
    }, timeout);

    try {
      // Check if connected
      const connected = await isUSBConnected();
      if (!connected) {
        clearTimeout(timeoutId);
        resolve({
          success: false,
          transactionId: message.payload?.transactionId || '',
          errorCode: 'USB_NOT_CONNECTED',
          errorMessage: 'USB not connected. Please connect POS via OTG cable.',
        });
        return;
      }

      // Build XML request based on command
      let xmlRequest: string;
      switch (message.command) {
        case 'PURCHASE':
          xmlRequest = buildPurchaseRequest(
            parseInt(message.payload?.amount || '0'),
            message.payload?.invoiceNumber,
            message.payload?.merchantReference
          );
          break;
        case 'GET_STATUS':
          xmlRequest = buildStatusRequest();
          break;
        case 'GET_TERMINAL_INFO':
          xmlRequest = buildTerminalInfoRequest();
          break;
        case 'RECONCILIATION':
          xmlRequest = buildReconciliationRequest();
          break;
        case 'LAST_TRANSACTION_STATUS':
          xmlRequest = buildLastTransactionRequest();
          break;
        case 'GET_TOTALS':
          xmlRequest = buildTotalsRequest();
          break;
        default:
          xmlRequest = `<?xml version="1.0" encoding="UTF-8"?><ECRMessage><CommandType>${ECR_COMMANDS[message.command] || message.command}</CommandType></ECRMessage>`;
      }

      console.log('[USB ECR] Sending XML command:', xmlRequest.substring(0, 200));

      // Set up response handler
      let responseReceived = false;
      const unsubscribe = onDataReceived((data: string) => {
        if (responseReceived) return;
        
        console.log('[USB ECR] Data received:', data.substring(0, 200));
        
        // Check for intermediate status messages
        if (data.includes('<IntermediateStatus>') || data.includes('<StatusCode>')) {
          const statusMatch = data.match(/<StatusCode>(\d+)<\/StatusCode>/);
          if (statusMatch) {
            const statusCode = statusMatch[1];
            const mappedStatus = mapIntermediateCode(statusCode);
            if (mappedStatus) {
              setIntermediateStatus(mappedStatus);
            }
          }
          return; // Don't resolve for intermediate messages
        }

        // Check for final response (contains ResponseCode or ErrorCode)
        if (data.includes('<ResponseCode>') || data.includes('<ErrorCode>') || data.includes('</ECRMessage>')) {
          responseReceived = true;
          clearTimeout(timeoutId);
          unsubscribe();
          
          try {
            const ecrResponse = parseECRXMLResponse(data);
            const response = convertECRToTransactionResponse(ecrResponse, message.payload?.transactionId || '');
            resolve(response);
          } catch (parseError) {
            console.error('[USB ECR] Parse error:', parseError);
            resolve({
              success: false,
              transactionId: message.payload?.transactionId || '',
              errorCode: 'PARSE_ERROR',
              errorMessage: 'Failed to parse POS response',
            });
          }
        }
      });

      // Send the command
      const sent = await writeUSBData(xmlRequest);
      
      if (!sent) {
        clearTimeout(timeoutId);
        unsubscribe();
        resolve({
          success: false,
          transactionId: message.payload?.transactionId || '',
          errorCode: 'USB_WRITE_FAILED',
          errorMessage: 'Failed to send command to POS via USB',
        });
      }
      
      console.log('[USB ECR] Command sent, waiting for response...');
    } catch (error: any) {
      clearTimeout(timeoutId);
      console.error('[USB ECR] Error:', error);
      resolve({
        success: false,
        transactionId: message.payload?.transactionId || '',
        errorCode: 'USB_ERROR',
        errorMessage: error.message || 'USB communication error',
      });
    }
  });
};

/**
 * Map POS status string to typed status
 */
const mapPOSStatus = (status: string): POSIntermediateStatus | null => {
  const statusMap: Record<string, POSIntermediateStatus> = {
    'INSERT_CARD': 'INSERT_CARD',
    'TAP_CARD': 'TAP_CARD',
    'SWIPE_CARD': 'SWIPE_CARD',
    'ENTER_PIN': 'ENTER_PIN',
    'PROCESSING': 'PROCESSING',
    'COMMUNICATING': 'COMMUNICATING_WITH_BANK',
    'REMOVE_CARD': 'REMOVE_CARD',
    'PRINTING': 'PRINTING_RECEIPT',
    'COMPLETE': 'TRANSACTION_COMPLETE',
  };
  
  return statusMap[status.toUpperCase()] || null;
};

/**
 * Parse XML response from OM-A880 POS
 */
const parseXMLResponse = (xmlResponse: any, transactionId: string): TransactionResponse => {
  // Handle raw XML parsing if string
  if (typeof xmlResponse === 'string') {
    // Parse XML string (placeholder - use DOMParser in production)
    console.log('Parsing XML response:', xmlResponse);
  }
  
  // Map response to unified format
  const success = xmlResponse.responseCode === '00' || xmlResponse.approved === true;
  
  return {
    success,
    transactionId,
    posRRN: xmlResponse.rrn || xmlResponse.RRN,
    posAuthCode: xmlResponse.authCode || xmlResponse.AuthCode || xmlResponse.approvalCode,
    posTID: xmlResponse.tid || xmlResponse.TID || xmlResponse.terminalId,
    posMID: xmlResponse.mid || xmlResponse.MID || xmlResponse.merchantId,
    posResponseCode: xmlResponse.responseCode,
    cardLastFour: xmlResponse.cardLastFour || xmlResponse.pan?.slice(-4),
    cardType: xmlResponse.cardType || xmlResponse.scheme,
    receiptData: xmlResponse.receiptData || xmlResponse.receipt,
    errorCode: success ? undefined : xmlResponse.responseCode,
    errorMessage: success ? undefined : xmlResponse.responseMessage,
    rawResponse: xmlResponse,
  };
};

/**
 * Simulate POS transaction for development/testing
 */
const simulatePOSTransaction = (
  message: POSMessage, 
  resolve: (response: TransactionResponse) => void
) => {
  console.log('Simulating POS transaction...', message);
  
  // Simulate intermediate statuses
  const statuses: POSIntermediateStatus[] = [
    'INITIALIZING',
    'TAP_CARD',
    'PROCESSING',
    'COMMUNICATING_WITH_BANK',
    'TRANSACTION_COMPLETE',
  ];
  
  let statusIndex = 0;
  const statusInterval = setInterval(() => {
    if (statusIndex < statuses.length) {
      setIntermediateStatus(statuses[statusIndex]);
      statusIndex++;
    } else {
      clearInterval(statusInterval);
    }
  }, 800);
  
  // Simulate final response after 4 seconds
  setTimeout(() => {
    clearInterval(statusInterval);
    
    // Simulation: Always fail in web context without native bridge
    resolve({
      success: false,
      transactionId: message.payload?.transactionId || '',
      errorCode: 'POS_NOT_AVAILABLE',
      errorMessage: 'جهاز الدفع غير متوفر. يرجى توصيل جهاز OM-A880.',
    });
  }, 4000);
};

/**
 * Get current transaction status
 */
export const getTransactionStatus = (): TransactionStatus => {
  return transactionStatus;
};

/**
 * Reset transaction status to idle
 */
export const resetTransactionStatus = () => {
  transactionStatus = 'idle';
  currentIntermediateStatus = null;
};

/**
 * Disconnect from POS
 */
export const disconnectPOS = async (): Promise<void> => {
  if (connectionCheckInterval) {
    clearInterval(connectionCheckInterval);
    connectionCheckInterval = null;
  }
  
  // Disconnect Ethernet if connected
  if (currentConfig?.connectionType === 'ethernet') {
    await disconnectEthernet();
  }
  
  setConnectionStatus('disconnected');
  currentConfig = null;
  
  console.log('POS disconnected');
};

/**
 * Test POS connection (Ethernet-first approach)
 */
export const testConnection = async (config: POSConfig): Promise<{ connected: boolean; message: string; status?: POSStatusResponse }> => {
  try {
    // ETHERNET is the PRIMARY connection method
    if (config.connectionType === 'ethernet' || (config.ipAddress && config.port)) {
      if (!config.ipAddress || !config.port) {
        return {
          connected: false,
          message: 'IP address and port are required for Ethernet connection',
        };
      }
      
      console.log(`Testing Ethernet connection to ${config.ipAddress}:${config.port}`);
      
      const result = await testEthernetConnection(
        config.ipAddress, 
        parseInt(config.port), 
        5000
      );
      
      if (!result.connected) {
        return {
          connected: false,
          message: result.error || `Unable to connect to ${config.ipAddress}:${config.port}. Please verify the IP and port settings.`,
        };
      }
      
      // Return terminal info if available
      if (result.terminalInfo) {
        const info = result.terminalInfo;
        return {
          connected: true,
          message: `POS connected successfully via Ethernet. TID: ${info.tid || 'N/A'}, MID: ${info.mid || 'N/A'}`,
          status: {
            ready: info.errorCode === 'E000',
            printerStatus: 'ok',
            readerStatus: 'ok',
            connectivity: 'online',
            terminalId: info.tid,
            merchantId: info.mid,
          },
        };
      }
      
      return {
        connected: true,
        message: `Connected to POS at ${config.ipAddress}:${config.port}`,
      };
    }
    
    // USB connection (secondary)
    if (config.connectionType === 'usb') {
      const detected = await detectUSBDevice();
      if (!detected) {
        return {
          connected: false,
          message: 'No USB POS device detected. Please connect the OM-A880 device.',
        };
      }
      
      return {
        connected: true,
        message: 'USB POS device detected',
      };
    }
    
    return {
      connected: false,
      message: 'No connection method configured. Please set IP address and port for Ethernet connection.',
    };
  } catch (error: any) {
    return {
      connected: false,
      message: error.message || 'Connection test failed',
    };
  }
};

/**
 * Receipt Strategy Configuration
 */
export type ReceiptStrategy = 'pos_prints' | 'kiosk_prints';

let receiptStrategy: ReceiptStrategy = 'pos_prints';

export const setReceiptStrategy = (strategy: ReceiptStrategy) => {
  receiptStrategy = strategy;
};

export const getReceiptStrategy = (): ReceiptStrategy => {
  return receiptStrategy;
};
