import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { ArrowLeft, Plus, Trash2, Edit, Eye, EyeOff, Info, Upload, X, GripVertical, ArrowUp, ArrowDown } from "lucide-react";
import { ThemeToggle } from "@/components/admin/ThemeToggle";

const CategoriesManagement = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [categories, setCategories] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [formData, setFormData] = useState({
    category_id: '',
    title: '',
    description: '',
    is_visible: true,
    display_order: 0,
    icon_url: '',
    info_text: ''
  });
  const [iconFile, setIconFile] = useState<File | null>(null);
  const [iconPreview, setIconPreview] = useState<string>('');

  useEffect(() => {
    checkAuth();
    loadCategories();
  }, []);

  const checkAuth = async () => {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) {
      navigate('/auth');
      return;
    }
  };

  const loadCategories = async () => {
    try {
      const { data, error } = await supabase
        .from('donation_categories')
        .select('*')
        .order('display_order', { ascending: true });

      if (error) throw error;
      setCategories(data || []);
    } catch (error: any) {
      toast({
        title: "Error loading categories",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleIconChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Check file size (max 100KB)
    if (file.size > 100 * 1024) {
      toast({
        title: "File too large",
        description: "Icon must be less than 100KB",
        variant: "destructive",
      });
      return;
    }

    // Check file type
    if (!['image/jpeg', 'image/jpg', 'image/png'].includes(file.type)) {
      toast({
        title: "Invalid file type",
        description: "Only JPG, JPEG, and PNG files are allowed",
        variant: "destructive",
      });
      return;
    }

    setIconFile(file);
    setIconPreview(URL.createObjectURL(file));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (categories.length >= 8 && !editingId) {
      toast({
        title: "Maximum categories reached",
        description: "You can only have up to 8 categories.",
        variant: "destructive",
      });
      return;
    }

    try {
      let iconUrl = formData.icon_url;

      // Upload icon if a new file is selected
      if (iconFile) {
        const fileName = `${formData.category_id}-${Date.now()}.${iconFile.name.split('.').pop()}`;
        const { error: uploadError } = await supabase.storage
          .from('category-icons')
          .upload(fileName, iconFile, { upsert: true });

        if (uploadError) throw uploadError;

        const { data: { publicUrl } } = supabase.storage
          .from('category-icons')
          .getPublicUrl(fileName);

        iconUrl = publicUrl;
      }

      const dataToSave = { ...formData, icon_url: iconUrl };

      if (editingId) {
        const { error } = await supabase
          .from('donation_categories')
          .update(dataToSave)
          .eq('id', editingId);

        if (error) throw error;
        toast({ title: "Category updated successfully" });
      } else {
        // category_reference will be auto-generated by trigger
        const { error } = await supabase
          .from('donation_categories')
          .insert([dataToSave] as any);

        if (error) throw error;
        toast({ title: "Category added successfully" });
      }

      resetForm();
      loadCategories();
    } catch (error: any) {
      toast({
        title: "Error saving category",
        description: error.message,
        variant: "destructive",
      });
    }
  };

  const handleEdit = (category: any) => {
    setEditingId(category.id);
    setFormData({
      category_id: category.category_id,
      title: category.title,
      description: category.description,
      is_visible: category.is_visible,
      display_order: category.display_order,
      icon_url: category.icon_url || '',
      info_text: category.info_text || ''
    });
    setIconPreview(category.icon_url || '');
    setIconFile(null);
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure you want to delete this category?')) return;

    try {
      const { error } = await supabase
        .from('donation_categories')
        .delete()
        .eq('id', id);

      if (error) throw error;
      toast({ title: "Category deleted successfully" });
      loadCategories();
    } catch (error: any) {
      toast({
        title: "Error deleting category",
        description: error.message,
        variant: "destructive",
      });
    }
  };

  const toggleVisibility = async (id: string, currentVisibility: boolean) => {
    try {
      const { error } = await supabase
        .from('donation_categories')
        .update({ is_visible: !currentVisibility })
        .eq('id', id);

      if (error) throw error;
      toast({ title: "Visibility updated" });
      loadCategories();
    } catch (error: any) {
      toast({
        title: "Error updating visibility",
        description: error.message,
        variant: "destructive",
      });
    }
  };

  const moveCategory = async (categoryId: string, direction: 'up' | 'down') => {
    const currentIndex = categories.findIndex(c => c.id === categoryId);
    if ((direction === 'up' && currentIndex === 0) || 
        (direction === 'down' && currentIndex === categories.length - 1)) {
      return;
    }

    const newIndex = direction === 'up' ? currentIndex - 1 : currentIndex + 1;
    const updatedCategories = [...categories];
    const [movedCategory] = updatedCategories.splice(currentIndex, 1);
    updatedCategories.splice(newIndex, 0, movedCategory);

    // Update display_order for all categories
    try {
      const updates = updatedCategories.map((cat, index) => ({
        id: cat.id,
        display_order: index + 1
      }));

      for (const update of updates) {
        const { error } = await supabase
          .from('donation_categories')
          .update({ display_order: update.display_order })
          .eq('id', update.id);

        if (error) throw error;
      }

      toast({ title: "Category order updated" });
      loadCategories();
    } catch (error: any) {
      toast({
        title: "Error updating category order",
        description: error.message,
        variant: "destructive",
      });
    }
  };

  const resetForm = () => {
    setEditingId(null);
    setFormData({
      category_id: '',
      title: '',
      description: '',
      is_visible: true,
      display_order: categories.length + 1,
      icon_url: '',
      info_text: ''
    });
    setIconFile(null);
    setIconPreview('');
  };

  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-6xl mx-auto">
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-4">
            <Button variant="ghost" onClick={() => navigate('/admin')}>
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Dashboard
            </Button>
            <h1 className="text-3xl font-bold">Manage Categories</h1>
          </div>
          <ThemeToggle />
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Form */}
          <Card className="p-6">
            <h2 className="text-xl font-bold mb-4">
              {editingId ? 'Edit Category' : 'Add New Category'}
            </h2>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <Label htmlFor="category_id">Category ID (English)</Label>
                <Input
                  id="category_id"
                  value={formData.category_id}
                  onChange={(e) => setFormData({ ...formData, category_id: e.target.value })}
                  required
                  disabled={!!editingId}
                  placeholder="e.g., zakat, sadaqah"
                />
              </div>

              <div>
                <Label htmlFor="title">Title (Arabic)</Label>
                <Input
                  id="title"
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  required
                  placeholder="عنوان الفئة"
                />
              </div>

              <div>
                <Label htmlFor="description">Description (Arabic)</Label>
                <Textarea
                  id="description"
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  required
                  placeholder="وصف الفئة"
                />
              </div>

              <div>
                <Label htmlFor="info_text">Information Text (Arabic)</Label>
                <Textarea
                  id="info_text"
                  value={formData.info_text}
                  onChange={(e) => setFormData({ ...formData, info_text: e.target.value })}
                  placeholder="معلومات إضافية عن الفئة"
                  rows={3}
                />
                <p className="text-sm text-muted-foreground mt-1">
                  This information will be shown when users click the info icon on the kiosk
                </p>
              </div>

              <div>
                <Label htmlFor="icon">Category Icon</Label>
                <div className="mt-2">
                  <Input
                    id="icon"
                    type="file"
                    accept=".jpg,.jpeg,.png"
                    onChange={handleIconChange}
                    className="mb-2"
                  />
                  <p className="text-sm text-muted-foreground">
                    Only JPG, JPEG, and PNG files. Maximum size: 100 KB
                  </p>
                </div>
                {iconPreview && (
                  <div className="mt-2 relative w-24 h-24">
                    <img 
                      src={iconPreview} 
                      alt="Icon preview" 
                      className="w-full h-full object-cover rounded-lg border-2 border-border"
                    />
                    <Button
                      type="button"
                      variant="destructive"
                      size="icon"
                      className="absolute -top-2 -right-2 h-6 w-6 rounded-full"
                      onClick={() => {
                        setIconFile(null);
                        setIconPreview('');
                        setFormData({ ...formData, icon_url: '' });
                      }}
                    >
                      <X className="h-3 w-3" />
                    </Button>
                  </div>
                )}
              </div>

              <div>
                <Label htmlFor="display_order">Display Order</Label>
                <Input
                  id="display_order"
                  type="number"
                  value={formData.display_order}
                  onChange={(e) => setFormData({ ...formData, display_order: parseInt(e.target.value) })}
                  required
                />
              </div>

              <div className="flex items-center space-x-2">
                <Switch
                  id="is_visible"
                  checked={formData.is_visible}
                  onCheckedChange={(checked) => setFormData({ ...formData, is_visible: checked })}
                />
                <Label htmlFor="is_visible">Visible to public</Label>
              </div>

              <div className="flex gap-2">
                <Button type="submit" className="flex-1">
                  {editingId ? 'Update' : 'Add'} Category
                </Button>
                {editingId && (
                  <Button type="button" variant="outline" onClick={resetForm}>
                    Cancel
                  </Button>
                )}
              </div>
            </form>
          </Card>

          {/* Categories List */}
          <div className="space-y-4">
            <h2 className="text-xl font-bold">
              Existing Categories ({categories.length}/8)
            </h2>
            {loading ? (
              <p>Loading...</p>
            ) : (
              categories.map((category, index) => (
                <Card key={category.id} className="p-4">
                  <div className="flex items-start gap-3">
                    {/* Reorder buttons */}
                    <div className="flex flex-col gap-1">
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => moveCategory(category.id, 'up')}
                        disabled={index === 0}
                        className="h-6 w-6 p-0"
                      >
                        <ArrowUp className="w-3 h-3" />
                      </Button>
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => moveCategory(category.id, 'down')}
                        disabled={index === categories.length - 1}
                        className="h-6 w-6 p-0"
                      >
                        <ArrowDown className="w-3 h-3" />
                      </Button>
                    </div>

                    {/* Category icon */}
                    {category.icon_url && (
                      <div className="w-12 h-12 rounded-lg overflow-hidden border-2 border-border flex-shrink-0">
                        <img 
                          src={category.icon_url} 
                          alt={category.title}
                          className="w-full h-full object-contain bg-white"
                        />
                      </div>
                    )}

                    {/* Category details */}
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-2">
                        <h3 className="text-lg font-bold">{category.title}</h3>
                        {category.is_visible ? (
                          <Eye className="w-4 h-4 text-success" />
                        ) : (
                          <EyeOff className="w-4 h-4 text-muted-foreground" />
                        )}
                      </div>
                      <p className="text-sm text-muted-foreground">{category.description}</p>
                      <div className="flex items-center gap-3 mt-1 text-xs text-muted-foreground">
                        <span>Ref: {category.category_reference || 'N/A'}</span>
                        <span>Order: {category.display_order}</span>
                      </div>
                    </div>

                    {/* Action buttons */}
                    <div className="flex gap-2">
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => toggleVisibility(category.id, category.is_visible)}
                      >
                        {category.is_visible ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      </Button>
                      <Button size="sm" variant="ghost" onClick={() => handleEdit(category)}>
                        <Edit className="w-4 h-4" />
                      </Button>
                      <Button size="sm" variant="ghost" onClick={() => handleDelete(category.id)}>
                        <Trash2 className="w-4 h-4 text-destructive" />
                      </Button>
                    </div>
                  </div>
                </Card>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default CategoriesManagement;